name: suggestion
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1


dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  freezed: ^2.4.1

flutter:
  uses-material-design: true
